// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace HardwareAnalyzer
{
	[default_interface]
	runtimeclass MainWindow : Microsoft.UI.Xaml.Window
	{
		MainWindow();
	}
}
